version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.1.0
  aws-cli: circleci/aws-cli@4.1.3
  node: circleci/node@5.2.0

jobs:
  deploy_react_app_on_ec2:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: SSH_Into_EC2
          command: ssh -o StrictHostKeyChecking=no -i ec2-user@3.83.20.127 './demo-react-ssh.sh'

workflows:
  build_push_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ${AWS_ECR_ACCOUNT_URL_REACT}
          aws-access-key-id: ${ACCESS_KEY_ID_REACT}
          aws-secret-access-key: ${SECRET_ACCESS_KEY_REACT}
          path: .
          region: ${AWS_REGION_REACT}
          repo: ${AWS_ECR_REACT_REPO}
          tag: 'latest,${CIRCLE_BUILD_NUM}'
          filters:
            branches:
              only: main

      - deployment_react_approval:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: main
              
      - deploy_react_app_on_ec2:
          requires:
            - deployment_react_approval
          filters:
            branches:
              only: main