orbs:                                                                                     
  aws-eks: circleci/aws-ecr@9.1.0
  aws-cli: circleci/aws-cli@4.1.3
  node: circleci/node@5.2.0
      
jobs:
  Deploy_React_App_On_EC2:
    machine:
      image: ubuntu-2004:202101-01
    steps:    
      - run:  
          name: SSH_Into_EC2
          command: ssh -o StrictHostKeyChecking=no -i ec2-user@3.83.20.127 './demo-react-ssh.sh'

version: 2.1    

workflows:      
  build_and_push_image:
    jobs:       
      - aws-ecr/build-and-push-react-image:
          account-url: AWS_ECR_ACCOUNT_URL_REACT
          aws-access-key-id: ACCESS_KEY_ID_REACT
          aws-secret-access-key: SECRET_ACCESS_KEY_REACT
          path: .
          no-output-timeout: 20m
          region: AWS_REGION_REACT
          repo: AWS_ECR_REACT_REPO
          skip-when-tage-exist: false
          tag: latest,$CIRCLE_BUILD_NUM
          filters:
            branches:
              only: main
      
      - Deployment_React_Approval:
          type: approval
          require:
            - aws-ecr/build_and_push_react_image
          filters:
            branches:
              only: main
              
      - Deploy_React_App_On_EC2:
          require:
            - Deployment_React_Approval
          filters:
            branches:
              only: main


