version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  node: circleci/node@5.2.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - aws-cli/setup
      - run:
          name: Build Docker image
          command: |
            docker build -t $AWS_ECR_REACT_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push image to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION_REACT | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL_REACT
            docker tag $AWS_ECR_REACT_REPO:$CIRCLE_SHA1 $AWS_ECR_ACCOUNT_URL_REACT/$AWS_ECR_REACT_REPO:$CIRCLE_SHA1
            docker push $AWS_ECR_ACCOUNT_URL_REACT/$AWS_ECR_REACT_REPO:$CIRCLE_SHA1

  deploy_react_app_on_ec2:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: SSH_Into_EC2
          command: ssh -o StrictHostKeyChecking=no -i ec2-user@3.83.20.127 './demo-react-ssh.sh'

workflows:
  build_push_and_deploy:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: master

      - deployment_react_approval:
          type: approval
          requires:
            - build_and_push_image
          filters:
            branches:
              only: master
              
      - deploy_react_app_on_ec2:
          requires:
            - deployment_react_approval
          filters:
            branches:
              only: master